name: LEX®
favicon: null
layout_spectrum: 0.00304
typography_spectrum: 0.16107
title: LEX®
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5778095631394535
  lightness: 0.457010185578838
  saturation: 0.9354903728235513
  rhythmicContrast: 0.5
purpose: []
